/*
 * Phylogenetics Tool suite
 * Copyright (C) 2013  UEA CMP Phylogenetics Group
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with this program.  If not, see
 * <http://www.gnu.org/licenses/>.
 */

package uk.ac.uea.cmp.phygen.tools.chopper;

import uk.ac.uea.cmp.phygen.core.ds.Taxa;
import uk.ac.uea.cmp.phygen.core.ds.quartet.Quartet;
import uk.ac.uea.cmp.phygen.core.ds.quartet.QuartetWeights;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.NumberFormat;
import java.util.LinkedList;

/**
 * Created with IntelliJ IDEA. User: Dan Date: 29/07/13 Time: 22:51 To change this template use File | Settings | File
 * Templates.
 */
public class ChoppedTree {

    private Taxa taxa;
    private QuartetWeights quartetWeights;
    private QuartetWeights summer;

    public ChoppedTree() {
        this(new Taxa(), new QuartetWeights(), new QuartetWeights());
    }

    public ChoppedTree(Taxa taxa, QuartetWeights quartetWeights, QuartetWeights summer) {
        this.taxa = taxa;
        this.quartetWeights = quartetWeights;
        this.summer = summer;
    }

    public Taxa getTaxa() {
        return taxa;
    }

    public QuartetWeights getQuartetWeights() {
        return quartetWeights;
    }

    public QuartetWeights getSummer() {
        return summer;
    }

    public void divide() {
        quartetWeights.divide(summer);
    }

    public void save(File outputPrefix) throws IOException {
        this.saveInformation(outputPrefix);
        this.saveQuartets(outputPrefix);
    }

    public void saveQuartets(File outputFile) throws IOException {

        int N = taxa.size();

        FileWriter out = new FileWriter(outputFile);

        out.write("taxanumber: " + N + ";\ndescription: supernetwork quartets generated by Chopper;\nsense: max;\n");

        NumberFormat nF = NumberFormat.getIntegerInstance();
        nF.setMinimumIntegerDigits(3);
        nF.setMaximumIntegerDigits(3);

        for (int n = 0; n < N; n++) {
            out.write("taxon:   " + nF.format(n + 1) + "   name: " + taxa.get(n).getName() + ";\n");
        }

        for (int a = 1; a <= N - 3; a++) {

            for (int b = a + 1; b <= N - 2; b++) {

                for (int c = b + 1; c <= N - 1; c++) {

                    for (int d = c + 1; d <= N; d++) {

                        out.write("quartet: " + nF.format(a) + " " + nF.format(b) + " " + nF.format(c) + " " + nF.format(d)
                                + " weights: "
                                + quartetWeights.getWeight(new Quartet(a, b, c, d)) + " " + quartetWeights.getWeight(new Quartet(a, c, b, d))
                                + " " + quartetWeights.getWeight(new Quartet(a, d, b, c)) + ";\n");

                    }
                }
            }
        }

        out.close();
    }

    public void saveInformation(File outputFile) throws IOException {

        int N = taxa.size();

        FileWriter out = new FileWriter(outputFile + ".info");

        out.write("taxanumber: " + N + ";\ndescription: supernetwork quartets presences generated by Chopper;\nsense: max;\n");

        NumberFormat nF = NumberFormat.getIntegerInstance();
        nF.setMinimumIntegerDigits(3);
        nF.setMaximumIntegerDigits(3);

        for (int n = 0; n < N; n++) {
            out.write("taxon:   " + nF.format(n + 1) + "   name: " + taxa.get(n) + ";\n");
        }

        for (int a = 1; a <= N - 3; a++) {

            for (int b = a + 1; b <= N - 2; b++) {

                for (int c = b + 1; c <= N - 1; c++) {

                    for (int d = c + 1; d <= N; d++) {

                        if (summer.getWeight(new Quartet(a, b, c, d)) > 0.0) {

                            out.write("quartet: " + nF.format(a) + " " + nF.format(b) + " " + nF.format(c) + " " + nF.format(d)
                                    + " weights: "
                                    + "1 1 1;\n");

                        } else {

                            out.write("quartet: " + nF.format(a) + " " + nF.format(b) + " " + nF.format(c) + " " + nF.format(d)
                                    + " weights: "
                                    + "0 0 0;\n");
                        }
                    }
                }
            }
        }

        out.close();
    }

}
